server:
  port: 8761
spring:
  profiles: first
  application:
    name: eureka-server
  security:
    user:
      name: kongTao
      password: 123456
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kongTao:123456@localhost:8762/eureka/
  instance:
    instanceId: ${spring.application.name}
---
server:
  port: 8762
spring:
  profiles: second
  application:
    name: eureka-server
  security:
    user:
      name: kongTao
      password: 123456
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kongTao:123456@localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}