spring:
  application:
    name: feign
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://kongTao:123456@localhost:8761/eureka/,http://kongTao:123456@localhost:8762/eureka/
  instance:
    instanceId: ${spring.application.name}